packages:
  - packages/*

blockExoticSubdeps: true

overrides:
  '@tootallnate/once@<3.0.1': '>=3.0.1'
  braces@<3.0.3: '>=3.0.3'
  form-data@<2.5.4: '>=2.5.4'
  marked@<4.0.10: '>=4.0.10'
  marked@>=0.3.14 <0.6.2: '>=0.6.2'
  micromatch@<4.0.8: '>=4.0.8'
  minimist@>=1.0.0 <1.2.6: '>=1.2.6'
  nth-check@<2.0.1: '>=2.0.1'
  qs@<6.14.1: '>=6.14.1'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver
  - '@octokit/endpoint@9.0.6'
  - rollup@2.80.0
