!: AUTO INIT
!: AUTO RESET
!: AUTO PULL_ALL

C: RUN "BEGIN" {"bookmark": "neo4j:bookmark:v1:tx94", "bookmarks": ["neo4j:bookmark:v1:tx5", "neo4j:bookmark:v1:tx29", "neo4j:bookmark:v1:tx94", "neo4j:bookmark:v1:tx56", "neo4j:bookmark:v1:tx16", "neo4j:bookmark:v1:tx68"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "CREATE (n {name:'Bob'})" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"bookmark": "neo4j:bookmark:v1:tx95"}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
