!: AUTO INIT
!: AUTO RESET
!: AUTO PULL_ALL

S: SUCCESS {"server": "Neo4j/3.1.0"}
C: RUN "CALL dbms.cluster.routing.getServers" {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9001","127.0.0.1:9002"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9001","127.0.0.1:9002"], "role": "READ"},{"addresses": ["127.0.0.1:9001","127.0.0.1:9002"], "role": "ROUTE"}]]
   SUCCESS {}
C: RUN "MATCH (n) RETURN n.name" {}
   PULL_ALL
S: SUCCESS {"fields": ["n.name"]}
   RECORD ["Bob"]
   RECORD ["Tina"]
   SUCCESS {}
