!: BOLT 3
!: AUTO HELLO
!: AUTO RESET
!: AUTO PULL_ALL
!: AUTO GOODBYE

C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx42"]}
C: RUN "CREATE (n {name:'Bob'})" {} {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
   SUCCESS {"bookmark": "neo4j:bookmark:v1:tx4242"}
C: COMMIT
S: SUCCESS {}
C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx4242"]}
C: RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   SUCCESS {"bookmark": "neo4j:bookmark:v1:tx424242"}
C: COMMIT
S: SUCCESS {}

