!: AUTO INIT
!: AUTO RESET
!: AUTO PULL_ALL

C: RUN "BEGIN" {"bookmark": "neo4j:bookmark:v1:tx42", "bookmarks": ["neo4j:bookmark:v1:tx42"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "CREATE (n {name:'Bob'})" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"bookmark": "neo4j:bookmark:v1:tx4242"}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "BEGIN" {"bookmark": "neo4j:bookmark:v1:tx99", "bookmarks": ["neo4j:bookmark:v1:tx99"]}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}
C: RUN "MATCH (n) RETURN n.name AS name" {}
   PULL_ALL
S: SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   SUCCESS {"bookmark": "neo4j:bookmark:v1:tx424242"}
C: RUN "COMMIT" {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {}

