name: Snyk Main Branch

on:
  push:
    branches: [ "5.0" ]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


jobs: 
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Snyk test dependencies
        run: snyk test --all-projects --strict-out-of-sync=false --severity-threshold=medium --fail-on=all

  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Snyk monitor dependencies
        run: snyk monitor --all-projects --strict-out-of-sync=false --target-reference=${GITHUB_REF}
