!: BOLT 3
!: AUTO HELLO
!: AUTO RESET
!: AUTO GOODBYE

C: RUN "CALL dbms.cluster.routing.getRoutingTable($context)" {"context": {"address": "127.0.0.1:9001"}} {}
   PULL_ALL
S: SUCCESS {"fields": ["ttl", "servers"]}
   RECORD [9223372036854775807, [{"addresses": ["127.0.0.1:9008"],"role": "WRITE"}, {"addresses": ["127.0.0.1:9001","127.0.0.1:9009","127.0.0.1:9010"], "role": "READ"},{"addresses": ["127.0.0.1:9001","127.0.0.1:9011"], "role": "ROUTE"}]]
   SUCCESS {}
C: BEGIN {"mode": "r"}
   RUN "MATCH (n) RETURN n.name AS name" {} {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"fields": ["name"]}
   RECORD ["Bob"]
   RECORD ["Alice"]
   SUCCESS {}
C: COMMIT
S: SUCCESS {}
