!: BOLT 3
!: AUTO HELLO
!: AUTO RESET
!: AUTO GOODBYE

C: BEGIN {"bookmarks": ["neo4j:bookmark:v1:tx5", "neo4j:bookmark:v1:tx29", "neo4j:bookmark:v1:tx94", "neo4j:bookmark:v1:tx56", "neo4j:bookmark:v1:tx16", "neo4j:bookmark:v1:tx68"]}
C: RUN "CREATE (n {name:'Bob'})" {} {}
   PULL_ALL
S: SUCCESS {}
   SUCCESS {"fields": []}
   SUCCESS {"bookmark": "neo4j:bookmark:v1:tx95"}
C: COMMIT
S: SUCCESS {}
